name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Running tests
      run: go test -cover -coverprofile=coverage.out ./...
    
    - name: Reporting coverage
      env: 
        CODECOV_TOKEN: 3a150f49-f275-4d42-a90b-4480067ab219
      run: bash <(curl -s https://codecov.io/bash)
