name: Doc

on:
  push:
    tags:
      - '*'

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Get the version
      id: get_version
      run: echo ${GITHUB_REF/refs\/tags\//}

